Repository googleapis/java-spanner, pull requests merged in 2020-02, with the labels that each got.

#55 chore: linkage monitor check should skipp clirr and enforcer
  .kokoro/linkage-monitor.sh
  synth.metadata
Labels: cla: yes

#59 deps: update core dependencies
  pom.xml
Labels: cla: yes

#57 fix: use resource type to identify type of error
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseNotFoundException.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionNotFoundException.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerException.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerExceptionFactory.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolStressTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerExceptionFactoryTest.java
Labels: cla: yes

#61 fix: stop sending RPCs on InstanceNotFound
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/InstanceNotFoundException.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerExceptionFactory.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerExceptionFactoryTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseTest.java
Labels: cla: yes

#54 feat: instrument Spanner client with OpenCensus metrics
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/MetricRegistryConstants.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/MetricRegistryTestUtils.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
Labels: cla: yes

#69 chore: only allow renovate-bot for trusted-contribution auto-labeling
  .github/trusted-contribution.yml
Labels: cla: yes

#66 docs(regen): update sample code to set total timeout, add API client header test
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/DatabaseAdminSettings.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/stub/DatabaseAdminStubSettings.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/instance/v1/InstanceAdminSettings.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/instance/v1/stub/InstanceAdminStubSettings.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/SpannerSettings.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/SpannerStubSettings.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/v1/SpannerClientTest.java
  synth.metadata
Labels: cla: yes

#65 feat: add session timeout metric
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/MetricRegistryConstants.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/MetricRegistryTestUtils.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
Labels: cla: yes

#80 chore: update common templates
  proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/Instance.java
  proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/InstanceOrBuilder.java
  proto-google-cloud-spanner-admin-instance-v1/src/main/proto/google/spanner/admin/instance/v1/spanner_instance_admin.proto
  synth.metadata
Labels: automerge, cla: yes

#82 chore: update common templates
  .kokoro/build.sh
  renovate.json
  synth.metadata
Labels: cla: yes

#75 Fix: multiple calls to end of span
  google-cloud-spanner/pom.xml
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClientImpl.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionClient.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/TraceUtil.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/FailOnOverkillTraceComponentImpl.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpanTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/TracerTest.java
Labels: cla: yes

#67 feat: add metrics to capture acquired and released sessions data
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/MetricRegistryConstants.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpanTest.java
Labels: cla: yes

#86 deps: keep OpenCensus at 0.24.0 until gRPC updates
  pom.xml
Labels: cla: yes

#85 fix: prevent potential thread starvation in SessionPool
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/BackendExhaustedTest.java
Labels: api: spanner, cla: yes
