Repository googleapis/java-spanner, pull requests merged in 2020-04, with the labels that each got.

#133 test: add VPC-SC test cases for backups
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITVPCNegativeTest.java
Labels: api: spanner, automerge, cla: yes

#134 perf: increase sessions in the pool in batches
  google-cloud-spanner/pom.xml
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionClient.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolOptions.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/BatchCreateSessionsTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionClientTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolBenchmark.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolLeakTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolStressTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpanTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionManagerImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionRunnerImplTest.java
Labels: api: spanner, cla: yes

#143 chore: update common templates
  .kokoro/common.sh
  .kokoro/nightly/integration.cfg
  synth.metadata
Labels: automerge, cla: yes

#141 fix: retry non-idempotent long-running RPCs
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseAdminClientTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseAdminGaxTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockDatabaseAdminServiceImpl.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseAdminTest.java
Labels: cla: yes

#153 fix: fix flaky test and remove warnings
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITSpannerOptionsTest.java
Labels: cla: yes

#149 tests: add test for session distribution
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionClientTest.java
Labels: cla: yes

#157 chore: update common templates
  .kokoro/common.sh
  .kokoro/dependencies.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  synth.metadata
Labels: automerge, cla: yes

#150 tests: benchmark should start the transaction
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolBenchmark.java
Labels: cla: yes

#160 fix: increase test timeout and remove warnings
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/RetryOnInvalidatedSessionTest.java
Labels: cla: yes

#159 fix: check for null input for Id classes
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/BackupId.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseId.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/InstanceConfigId.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/InstanceId.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionClient.java
Labels: cla: yes

#161 fix: wait for initialization to finish before test
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITSpannerOptionsTest.java
Labels: cla: yes

#137 samples: fix samples library versions
  pom.xml
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
Labels: automerge, cla: yes

#162 fix: clean up test instance if creation failed
  google-cloud-spanner/clirr-ignored-differences.xml
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/InstanceAdminClient.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/InstanceAdminClientImpl.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestEnv.java
Labels: cla: yes

#152 perf: prepare sessions with r/w tx in-process
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
Labels: cla: yes

#170 fix: StatementParser did not accept multiple query hints
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/StatementParser.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/StatementParserTest.java
Labels: cla: yes

#172 feat(deps): import shared-dependencies bom and use maven-flatten-plugin
  .gitignore
  google-cloud-spanner/pom.xml
  grpc-google-cloud-spanner-admin-database-v1/pom.xml
  grpc-google-cloud-spanner-admin-instance-v1/pom.xml
  grpc-google-cloud-spanner-v1/pom.xml
  pom.xml
  proto-google-cloud-spanner-admin-database-v1/pom.xml
  proto-google-cloud-spanner-admin-instance-v1/pom.xml
  proto-google-cloud-spanner-v1/pom.xml
Labels: cla: yes

#180 fix: create filter in correct order
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseAdminGaxTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceAdminGaxTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockDatabaseAdminServiceImpl.java
Labels: cla: yes

#181 fix: stop preparing session on most errors
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
Labels: cla: yes

#183 fix: remove error message checking
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITCommitTimestampTest.java
Labels: cla: yes

#184 tests: Attempt to fix random timeouts in ITBackup
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBackupTest.java
Labels: cla: yes
