Repository googleapis/java-spanner, pull requests merged in 2020-11, with the labels that each got.

#568 test: allow partial statements on the mock server
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
Labels: api: spanner, cla: yes

#572 test: check that page actually contains an element
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseAdminTest.java
Labels: cla: yes

#560 chore: updates samples
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/com/example/spanner/AddNumericColumnSample.java
  samples/snippets/src/main/java/com/example/spanner/AsyncQueryToListAsyncExample.java
  samples/snippets/src/main/java/com/example/spanner/CreateInstanceExample.java
  samples/snippets/src/main/java/com/example/spanner/QueryWithNumericParameterSample.java
  samples/snippets/src/main/java/com/example/spanner/SpannerSample.java
  samples/snippets/src/main/java/com/example/spanner/UpdateNumericDataSample.java
  samples/snippets/src/test/java/com/example/spanner/AsyncExamplesIT.java
  samples/snippets/src/test/java/com/example/spanner/QuickstartSampleIT.java
  samples/snippets/src/test/java/com/example/spanner/SpannerSampleIT.java
  samples/snippets/src/test/java/com/example/spanner/SpannerStandaloneExamplesIT.java
Labels: api: spanner, cla: yes, samples

#575 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, cla: yes

#580 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: spanner, cla: yes, context: full

#579 fix: make enums in the Connection API public
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/AutocommitDmlMode.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/TransactionMode.java
Labels: api: spanner, cla: yes

#609 docs: add descriptions for connection URL properties
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionOptions.java
Labels: api: spanner, cla: yes

#611 test: add profile for generating test sql scripts
  google-cloud-spanner/pom.xml
Labels: api: spanner, cla: yes

#610 fix: adds api spanner team as samples code owners
  .github/CODEOWNERS
Labels: api: spanner, cla: yes

#613 fix: updates project / instance for samples tests
  .kokoro/nightly/java11-samples.cfg
  .kokoro/nightly/java8-samples.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/presubmit/java11-samples.cfg
  .kokoro/presubmit/java8-samples.cfg
  .kokoro/presubmit/samples.cfg
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/test/java/com/example/spanner/QuickstartSampleIT.java
  synth.py
Labels: api: spanner, cla: yes

#582 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, cla: yes

#618 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#612 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: api: spanner, cla: yes, context: full

#621 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#616 fix: session retry could cause infinite wait
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncTransactionManagerImpl.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolAsyncTransactionManager.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionContextFutureImpl.java
Labels: api: spanner, cla: yes

#629 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#633 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#634 Revert "fix: skip failing backup tests for now"
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseAdminTest.java
Labels: api: spanner, cla: yes

#640 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#622 fix: delete stale sample databases
  samples/snippets/src/test/java/com/example/spanner/SpannerSampleIT.java
  samples/snippets/src/test/java/com/example/spanner/SpannerStandaloneExamplesIT.java
Labels: api: spanner, cla: yes, samples

#643 fix: query could hang transaction if ResultSet#next() is not called
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/GrpcResultSetTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginTransactionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/ReadFormatTestRunner.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/ResumableStreamIteratorTest.java
Labels: api: spanner, cla: yes

#631 fix: does not generate codeowners
  synth.py
Labels: api: spanner, cla: yes

#648 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#664 test: fix flaky InlineBeginTransactionTest
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginTransactionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
Labels: api: spanner, cla: yes

#639 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: spanner, cla: yes, context: full, context: partial

#668 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#670 test: test stream retries in combination with inlined begin
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginTransactionTest.java
Labels: api: spanner, cla: yes

#672 fix: fixes changelog for upgrade 2.0.0
  CHANGELOG.md
Labels: api: spanner, cla: yes

#667 chore(java): enable blunderbuss for samples and backoff retry for staging releases
  .github/blunderbuss.yml
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: spanner, cla: yes, context: full

#669 feat: retry admin request limit exceeded error
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AdminRequestsPerMinuteExceededException.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerExceptionFactory.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
Labels: api: spanner, cla: yes

#671 feat: allow lenient mode for connection properties
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionOptions.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionOptionsTest.java
Labels: api: spanner, cla: yes
