Repository googleapis/java-spanner, pull requests merged in 2020-06, with the labels that each got.

#237 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#214 fix: test allowed a too old staleness
  google-cloud-spanner/src/test/resources/com/google/cloud/spanner/connection/ITReadOnlySpannerTest.sql
Labels: cla: yes

#244 chore: document OpenCensus Metrics
  README.md
Labels: cla: yes

#252 fix: backend now supports optimizer version for DML
  .kokoro/build.sh
  google-cloud-spanner-bom/pom.xml
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITQueryOptionsTest.java
  grpc-google-cloud-spanner-admin-database-v1/pom.xml
  grpc-google-cloud-spanner-admin-instance-v1/pom.xml
  grpc-google-cloud-spanner-v1/pom.xml
  pom.xml
  samples/install-without-bom/pom.xml
  samples/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
Labels: cla: yes

#253 deps: include test-jar in bom
  google-cloud-spanner-bom/pom.xml
Labels: cla: yes

#128 feat: add num_sessions_in_pool metric
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/MetricRegistryConstants.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/MetricRegistryTestUtils.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
Labels: cla: yes

#260 fix: use millis to prevent rounding errors
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerRetryHelper.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerRetryHelperTest.java
Labels: cla: yes

#261 fix: include an explicit version for javax-annotations-api
  google-cloud-spanner-bom/pom.xml
  google-cloud-spanner/pom.xml
  grpc-google-cloud-spanner-v1/pom.xml
Labels: cla: yes

#262 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#265 test: get write sessions in one call
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
Labels: cla: yes

#266 test: try to workaround sleep bug in windows
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerRetryHelperTest.java
Labels: cla: yes

#268 tests: prevent multiple retries quickly after each other
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceAdminGaxTest.java
Labels: cla: yes

#247 chore: remove usage of deprecated ExpectedException none() method
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/AbstractStructReaderTypesTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/BackupIdTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/BackupTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseIdTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/GrpcResultSetTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceConfigIdTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceIdTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/KeyRangeTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/MutationTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/OperationTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/OptionsTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/PartitionOptionsTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/ResultSetsTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/ResumableStreamIteratorTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolIntegrationTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolOptionsTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpanTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerGaxRetryTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/StatementTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/StructTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/TimestampBoundTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionManagerImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/TypeTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/ValueTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/DdlBatchTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/DmlBatchTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ReadOnlyTransactionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ReadWriteTransactionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/StatementResultImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/StatementTimeoutTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/it/ITReadOnlySpannerTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/it/ITReadWriteAutocommitSpannerTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/it/ITTransactionModeTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBackupTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITClosedSessionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseAdminTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITInstanceAdminTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITQueryOptionsTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITQueryTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITReadOnlyTxnTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITReadTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITTransactionManagerTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITWriteTest.java
Labels: cla: yes

#271 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#279 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#281 process: also test deps on Java 11
  google-cloud-spanner/pom.xml
  grpc-google-cloud-spanner-admin-database-v1/pom.xml
  grpc-google-cloud-spanner-admin-instance-v1/pom.xml
  grpc-google-cloud-spanner-v1/pom.xml
Labels: cla: yes

#304 test: unskip tests passing against the emulator
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBatchDmlTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBatchReadTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDMLTest.java
Labels: cla: yes

#303 tests: fix flaky instance admin test
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceAdminGaxTest.java
Labels: cla: yes

#302 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies and update ExecutorProvider
  google-cloud-spanner/pom.xml
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsThreadTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/AbstractMockServerTest.java
  grpc-google-cloud-spanner-v1/pom.xml
  pom.xml
Labels: cla: yes

#301 feat: increase the max length of debug string
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/Value.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/ValueTest.java
Labels: cla: yes

#289 ci(java): run dependency test on Java 8 and 11
  .github/workflows/ci.yaml
  .kokoro/dependencies.sh
  README.md
  synth.metadata
Labels: cla: yes, context: partial

#309 tests: enable Connection API ITs
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ITAbstractSpannerTest.java
Labels: cla: yes

#311 chore: regenerate README versions
  README.md
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/admin/database/v1/DatabaseAdminClientTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/admin/instance/v1/InstanceAdminClientTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/v1/SpannerClientTest.java
  synth.metadata
Labels: automerge, cla: yes, context: none

#310 test: run integration tests against emulator
  .github/workflows/integration-tests-against-emulator.sh
  .github/workflows/integration-tests-against-emulator.yaml
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/testing/RemoteSpannerHelper.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestEnv.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ITAbstractSpannerTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/it/ITBulkConnectionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/it/ITReadOnlySpannerTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/it/ITSqlMusicScriptTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/it/ITSqlScriptTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/it/ITTransactionModeTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/it/ITTransactionRetryTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITCommitTimestampTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITWriteTest.java
Labels: cla: yes

#287 perf: use streaming RPC for PDML
  google-cloud-spanner/clirr-ignored-differences.xml
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/PartitionedDMLTransaction.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerExceptionFactory.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerRpc.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
Labels: cla: yes

#192 feat: support setting compression option
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/EncodingInterceptor.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerInterceptorProvider.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITSpannerOptionsTest.java
Labels: cla: yes
