Repository googleapis/java-spanner, pull requests merged in 2020-07, with the labels that each got.

#316 fix: set default values for streaming retry
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
Labels: cla: yes

#320 test: skip autocommit timeout test on emulator
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/it/ITReadWriteAutocommitSpannerTest.java
Labels: cla: yes

#319 test: clean up system-test setup against emulator
  .github/workflows/integration-tests-against-emulator.sh
  .github/workflows/integration-tests-against-emulator.yaml
Labels: automerge, cla: yes, type: cleanup

#317 chore: re-generated to pick up changes from self
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#328 deps: update shared config to 0.9.2
  google-cloud-spanner/pom.xml
  pom.xml
Labels: cla: yes

#331 tests: fix vpc test failure
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITVPCNegativeTest.java
Labels: cla: yes

#333 test: fix potential race condition in Async ResultSet
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncResultSetImpl.java
Labels: cla: yes

#339 fix: set gRPC keep-alive to 120 seconds
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
Labels: cla: yes

#337 fix: fix potential unnecessary transaction retry
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
Labels: cla: yes

#345 fix: runs sample tests in java 8 and java 11
  .kokoro/continuous/samples/common.cfg
  .kokoro/continuous/samples/samples-java11.cfg
  .kokoro/continuous/samples/samples-java8.cfg
  .kokoro/nightly/samples/common.cfg
  .kokoro/nightly/samples/samples-java11.cfg
  .kokoro/nightly/samples/samples-java8.cfg
  .kokoro/presubmit/samples/common.cfg
  .kokoro/presubmit/samples/samples-java11.cfg
  .kokoro/presubmit/samples/samples-java8.cfg
Labels: cla: yes

#329 chore: re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#340 fix: check if emulator is running if env var is set
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
Labels: cla: yes

#342 test: fix flaky ITTransactionRetryTest
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/it/ITTransactionRetryTest.java
Labels: cla: yes

#348 refactor: normalises samples config names
  .kokoro/continuous/java11-samples.cfg
  .kokoro/continuous/java8-samples.cfg
  .kokoro/continuous/samples/samples-java11.cfg
  .kokoro/continuous/samples/samples-java8.cfg
  .kokoro/nightly/java11-samples.cfg
  .kokoro/nightly/java8-samples.cfg
  .kokoro/nightly/samples/samples-java11.cfg
  .kokoro/nightly/samples/samples-java8.cfg
  .kokoro/presubmit/java11-samples.cfg
  .kokoro/presubmit/java8-samples.cfg
  .kokoro/presubmit/samples/samples-java11.cfg
  .kokoro/presubmit/samples/samples-java8.cfg
Labels: cla: yes

#349 feat: spanner NUMERIC type
  README.md
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/Type.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/TypeCode.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/TypeOrBuilder.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/TypeProto.java
  proto-google-cloud-spanner-v1/src/main/proto/google/spanner/v1/type.proto
  synth.metadata
Labels: automerge, cla: yes, context: full, context: partial

#338 fix: respect PDML timeout when using streaming RPC
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/PartitionedDMLTransaction.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/PartitionedDmlTransactionTest.java
Labels: cla: yes

#193 feat: add support for NUMERIC data type
  google-cloud-spanner/clirr-ignored-differences.xml
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractStructReader.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/ForwardingStructReader.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/Key.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/ResultSets.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/Struct.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/StructReader.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/Type.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/Value.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/ValueBinder.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ChecksumResultSet.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/DirectExecuteResultSet.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ReplaceableForwardingResultSet.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/AbstractStructReaderTypesTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/GrpcResultSetTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/KeyTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/ReadFormatTestRunner.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/ResultSetsTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SelectRandomBenchmark.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/StandardBenchmarkMockServer.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/TypeTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/ValueBinderTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/ValueTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/DirectExecuteResultSetTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/RandomResultSetGenerator.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ReadWriteTransactionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ReplaceableForwardingResultSetTest.java
  google-cloud-spanner/src/test/resources/com/google/cloud/spanner/read_tests.json
Labels: api: spanner, cla: yes

#347 test: rename integration test
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/ITSessionPoolIntegrationTest.java
Labels: cla: yes

#355 feat: include SQL statement in error message
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerExceptionFactory.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
Labels: cla: yes

#364 chore: re-generated to pick up changes from googleapis
  README.md
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/stub/DatabaseAdminStubSettings.java
  synth.metadata
Labels: cla: yes, context: partial

#365 fix: remove custom timeout and retry settings
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
Labels: cla: yes

#361 refactor: removes double loop of pdml transaction
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/PartitionedDMLTransaction.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/PartitionedDmlTransaction.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/PartitionedDmlTransactionTest.java
Labels: cla: yes

#362 deps: stop auto updates of commons-lang3
  renovate.json
Labels: cla: yes

#367 fix: remove unused kokoro files
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11-samples.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-samples.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/propose_release.sh
  .kokoro/continuous/samples.cfg
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/presubmit/samples.cfg
Labels: cla: yes

#360 fix: retry pdml transaction on EOS internal error
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/IsRetryableInternalError.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/IsSslHandshakeException.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/PartitionedDmlTransaction.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerExceptionFactory.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/IsRetryableInternalErrorTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/IsSslHandshakeExceptionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/PartitionedDmlTransactionTest.java
Labels: cla: yes

#369 cleanup: removes unnecessary comments
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/IsRetryableInternalError.java
Labels: cla: yes
