Repository googleapis/java-spanner, pull requests merged in 2020-05, with the labels that each got.

#173 chore: generate README from synth.py
  .readme-partials.yaml
  .repo-metadata.json
  README.md
  synth.metadata
  synth.py
Labels: cla: yes

#174 fix: set resource type for database parameter of Backup
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/admin/database/v1/DatabaseAdminClientTest.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/Backup.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/BackupOrBuilder.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/BackupProto.java
  proto-google-cloud-spanner-admin-database-v1/src/main/proto/google/spanner/admin/database/v1/backup.proto
  synth.metadata
Labels: cla: yes

#195 fix: make it possible to override backups methods
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
Labels: api: spanner, automerge, cla: yes

#209 chore: bump Spanner version for samples without bom
  samples/install-without-bom/pom.xml
Labels: cla: yes

#205 tests: fix flaky restoreTestDatabase failures
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseAdminClientTest.java
Labels: cla: yes

#204 fix: use nanos to prevent truncation errors
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerRetryHelperTest.java
Labels: cla: yes

#198 feat: mark when a Spanner client is closed
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClientImpl.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolIntegrationTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolStressTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerImplTest.java
Labels: cla: yes

#203 fix: Partitioned DML timeout was not always respected
  google-cloud-spanner/clirr-ignored-differences.xml
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/PartitionedDMLTransaction.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerRpc.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
Labels: cla: yes

#206 fix: reuse clientId for invalidated databases
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerImplTest.java
Labels: cla: yes

#208 tests: increase timeout to prevent flakiness
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
Labels: cla: yes

#213 fix: partitionedDml stub was not closed
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
Labels: cla: yes

#232 fix: PDML retry settings were not applied for aborted tx
  google-cloud-spanner/clirr-ignored-differences.xml
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/PartitionedDMLTransaction.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerRetryHelper.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerRpc.java
Labels: cla: yes

#235 fix: remove the need for any env var in all tests
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
Labels: cla: yes

#212 tests: add additional tests for client ids
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerImplTest.java
Labels: cla: yes

#233 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#241 tests: enable integration tests with the emulator
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/testing/RemoteSpannerHelper.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBackupTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBatchDmlTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBatchReadTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITClosedSessionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITCommitTimestampTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDMLTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseAdminTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITInstanceAdminTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITQueryOptionsTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITQueryTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITTransactionManagerTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITTransactionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITVPCNegativeTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITWriteTest.java
Labels: cla: yes
