Repository googleapis/java-spanner, pull requests merged in 2020-09, with the labels that each got.

#413 test: add integration tests for numeric
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITWriteTest.java
Labels: api: spanner, cla: yes

#408 chore: fix OpenCensus metrics list
  README.md
Labels: api: spanner, cla: yes

#405 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  README.md
  synth.metadata
Labels: api: spanner, cla: yes, context: partial

#416 fix: iterate over async result set in sync
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncResultSetImpl.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
Labels: api: spanner, cla: yes

#396 feat: Add experimental DirectPath support
  google-cloud-spanner/pom.xml
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/GceTestEnvConfig.java
Labels: api: spanner, cla: yes

#415 docs: updates bom version and spanner version in the readme
  README.md
  synth.metadata
Labels: api: spanner, cla: yes, context: none

#411 Remove Guava ImmutableList from API surface.
  google-cloud-spanner/clirr-ignored-differences.xml
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncResultSet.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncResultSetImpl.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/ForwardingAsyncResultSet.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncResultSetImplStressTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncResultSetImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncRunnerTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncTransactionManagerTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/ReadAsyncTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/RetryOnInvalidatedSessionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITAsyncExamplesTest.java
Labels: api: spanner, cla: yes

#421 fix: fix aborted handling of batchUpdateAsync
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncTransactionManagerTest.java
Labels: api: spanner, cla: yes

#426 fix: uses old version of gax-grpc method
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
Labels: cla: yes

#423 feat: add lazy initializer
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractLazyInitializer.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/LazySpannerInitializer.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/LazySpannerInitializerTest.java
Labels: api: spanner, cla: yes

#422 chore: updates bom version to 10.1.0
  README.md
  synth.metadata
Labels: api: spanner, cla: yes, context: none

#425 fix: do not close delegate rs in callback runnable
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncResultSetImpl.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncResultSetImplStressTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncResultSetImplTest.java
Labels: api: spanner, cla: yes

#438 fix: re-adds method used in internal testing
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
Labels: cla: yes

#424 fix: improve numeric range checks
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/Value.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/GrpcResultSetTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/ValueTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITQueryTest.java
Labels: api: spanner, cla: yes

#433 chore: updates spanner dependency version in README file
  README.md
  synth.metadata
Labels: api: spanner, cla: yes, context: none

#443 chore: regenerate common templates
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#454 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#455 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: spanner, automerge, cla: yes

#430 fix: use credentials key in pool
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionOptions.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SpannerPool.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/ResumableStreamIteratorTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/SpannerPoolTest.java
Labels: api: spanner, cla: yes

#463 fix: skip failing backup tests for now
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseAdminTest.java
Labels: cla: yes

#462 chore: adds api-spanner-java group as codeowners
  .github/CODEOWNERS
  .repo-metadata.json
Labels: cla: yes
