Repository googleapis/java-spanner, pull requests merged in 2020-03, with the labels that each got.

#84 feat: add QueryOptions proto
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/instance/v1/InstanceAdminClient.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/SpannerClient.java
  grpc-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/DatabaseAdminGrpc.java
  grpc-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/SpannerGrpc.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/CreateDatabaseRequest.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/DropDatabaseRequest.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/GetDatabaseDdlRequest.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/GetDatabaseDdlResponse.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/GetDatabaseRequest.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/ListDatabasesRequest.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/ListDatabasesRequestOrBuilder.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/ListDatabasesResponse.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/ListDatabasesResponseOrBuilder.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/UpdateDatabaseDdlRequest.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/UpdateDatabaseDdlRequestOrBuilder.java
  proto-google-cloud-spanner-admin-database-v1/src/main/proto/google/spanner/admin/database/v1/spanner_database_admin.proto
  proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/GetInstanceRequest.java
  proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/GetInstanceRequestOrBuilder.java
  proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/UpdateInstanceRequest.java
  proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/UpdateInstanceRequestOrBuilder.java
  proto-google-cloud-spanner-admin-instance-v1/src/main/proto/google/spanner/admin/instance/v1/spanner_instance_admin.proto
  proto-google-cloud-spanner-v1/clirr-ignored-differences.xml
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/BatchCreateSessionsRequest.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/BatchCreateSessionsRequestOrBuilder.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/BatchCreateSessionsResponse.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/BeginTransactionRequest.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ExecuteBatchDmlRequest.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ExecuteBatchDmlRequestOrBuilder.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ExecuteBatchDmlResponse.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ExecuteBatchDmlResponseOrBuilder.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ExecuteSqlRequest.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ExecuteSqlRequestOrBuilder.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ListSessionsRequest.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ListSessionsRequestOrBuilder.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ListSessionsResponse.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ListSessionsResponseOrBuilder.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/Mutation.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/MutationOrBuilder.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/PartitionQueryRequest.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/PartitionQueryRequestOrBuilder.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/PartitionReadRequest.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/PartitionReadRequestOrBuilder.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ReadRequest.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/ReadRequestOrBuilder.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/SpannerProto.java
  proto-google-cloud-spanner-v1/src/main/proto/google/spanner/v1/keys.proto
  proto-google-cloud-spanner-v1/src/main/proto/google/spanner/v1/mutation.proto
  proto-google-cloud-spanner-v1/src/main/proto/google/spanner/v1/query_plan.proto
  proto-google-cloud-spanner-v1/src/main/proto/google/spanner/v1/result_set.proto
  proto-google-cloud-spanner-v1/src/main/proto/google/spanner/v1/spanner.proto
  proto-google-cloud-spanner-v1/src/main/proto/google/spanner/v1/transaction.proto
  proto-google-cloud-spanner-v1/src/main/proto/google/spanner/v1/type.proto
  synth.metadata
Labels: cla: yes

#90 feat: add backend query options
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/BatchClientImpl.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionClient.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/Statement.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/AbstractReadContextTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionContextImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionManagerImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionRunnerImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITQueryOptionsTest.java
Labels: api: spanner, cla: yes

#98 fix: never use credentials in combination with plain text
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
Labels: cla: yes

#97 feat: add Backups protos and APIs
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/DatabaseAdminClient.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/DatabaseAdminSettings.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/package-info.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/stub/DatabaseAdminStub.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/stub/DatabaseAdminStubSettings.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/stub/GrpcDatabaseAdminStub.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/admin/database/v1/DatabaseAdminClientTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/admin/database/v1/MockDatabaseAdminImpl.java
  grpc-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/DatabaseAdminGrpc.java
  proto-google-cloud-spanner-admin-database-v1/clirr-ignored-differences.xml
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/Backup.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/BackupInfo.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/BackupInfoOrBuilder.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/BackupName.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/BackupOrBuilder.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/BackupProto.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/CommonProto.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/CreateBackupMetadata.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/CreateBackupMetadataOrBuilder.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/CreateBackupRequest.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/CreateBackupRequestOrBuilder.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/CreateDatabaseRequest.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/CreateDatabaseRequestOrBuilder.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/Database.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/DatabaseOrBuilder.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/DeleteBackupRequest.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/DeleteBackupRequestOrBuilder.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/GetBackupRequest.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/GetBackupRequestOrBuilder.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/ListBackupOperationsRequest.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/ListBackupOperationsRequestOrBuilder.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/ListBackupOperationsResponse.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/ListBackupOperationsResponseOrBuilder.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/ListBackupsRequest.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/ListBackupsRequestOrBuilder.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/ListBackupsResponse.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/ListBackupsResponseOrBuilder.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/ListDatabaseOperationsRequest.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/ListDatabaseOperationsRequestOrBuilder.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/ListDatabaseOperationsResponse.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/ListDatabaseOperationsResponseOrBuilder.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/OperationProgress.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/OperationProgressOrBuilder.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/OptimizeRestoredDatabaseMetadata.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/OptimizeRestoredDatabaseMetadataOrBuilder.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/RestoreDatabaseMetadata.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/RestoreDatabaseMetadataOrBuilder.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/RestoreDatabaseRequest.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/RestoreDatabaseRequestOrBuilder.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/RestoreInfo.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/RestoreInfoOrBuilder.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/RestoreSourceType.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/SpannerDatabaseAdminProto.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/UpdateBackupRequest.java
  proto-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/UpdateBackupRequestOrBuilder.java
  proto-google-cloud-spanner-admin-database-v1/src/main/proto/google/spanner/admin/database/v1/backup.proto
  proto-google-cloud-spanner-admin-database-v1/src/main/proto/google/spanner/admin/database/v1/common.proto
  proto-google-cloud-spanner-admin-database-v1/src/main/proto/google/spanner/admin/database/v1/spanner_database_admin.proto
  synth.metadata
Labels: cla: yes

#102 chore: update PR template
  .github/PULL_REQUEST_TEMPLATE.md
  synth.metadata
Labels: automerge, cla: yes

#105 fix: use grpc 1.27.2 to prevent version conflicts
  pom.xml
Labels: cla: yes

#113 samples: fix snippet closing tag
  samples/install-without-bom/pom.xml
Labels: automerge, cla: yes

#100 feat: add backup support
  google-cloud-spanner/clirr-ignored-differences.xml
  google-cloud-spanner/pom.xml
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/Backup.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/BackupId.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/BackupInfo.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/Database.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseAdminClient.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseAdminClientImpl.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseInfo.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/Instance.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/Options.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/RestoreInfo.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/SpannerRpc.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/testing/RemoteSpannerHelper.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/BackupIdTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/BackupTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseAdminClientImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseAdminClientTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/GceTestEnvConfig.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/InstanceTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockDatabaseAdminServiceImpl.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockDatabaseAdminServiceImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockOperationsServiceImpl.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/ParallelIntegrationTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBackupTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBatchDmlTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBatchReadTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITClosedSessionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITCommitTimestampTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDMLTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseAdminTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITLargeReadTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITQueryOptionsTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITQueryTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITReadOnlyTxnTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITReadTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITSpannerOptionsTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITTransactionManagerTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITTransactionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITWriteTest.java
Labels: api: spanner, cla: yes

#117 fix: add client id to metrics to avoid collisions
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClientImpl.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/MetricRegistryConstants.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestWithClosedSessionsEnv.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerImplTest.java
Labels: automerge, cla: yes

#114 chore: use java helper for templates
  synth.py
Labels: cla: yes

#119 fix: retry restore if blocked by pending restore
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBackupTest.java
Labels: cla: yes

#121 chore: enable context aware commits
  synth.py
Labels: automerge, cla: yes

#126 chore: update common templates
  .kokoro/build.sh
  .kokoro/common.sh
  .kokoro/dependencies.sh
  .kokoro/linkage-monitor.sh
  renovate.json
  synth.metadata
Labels: automerge, cla: yes

#129 tests: assign unique id's per test case
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDMLTest.java
Labels: cla: yes

#125 chore: Migrate spanner synth.py to bazel
  grpc-google-cloud-spanner-admin-database-v1/clirr-ignored-differences.xml
  grpc-google-cloud-spanner-admin-database-v1/src/main/java/com/google/spanner/admin/database/v1/DatabaseAdminGrpc.java
  grpc-google-cloud-spanner-admin-instance-v1/clirr-ignored-differences.xml
  grpc-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/InstanceAdminGrpc.java
  grpc-google-cloud-spanner-v1/clirr-ignored-differences.xml
  grpc-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/SpannerGrpc.java
  synth.py
Labels: cla: yes
