Repository googleapis/java-spanner, pull requests merged in 2020-08, with the labels that each got.

#372 chore: re-generated to pick up changes from synthtool
  .kokoro/dependencies.sh
  .kokoro/nightly/samples.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  renovate.json
  synth.metadata
Labels: cla: yes, context: partial, do not merge

#377 test: skip test on emulator
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
Labels: cla: yes

#380 fix: enables emulator tests
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/testing/EmulatorSpannerHelper.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/testing/RemoteSpannerHelper.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestEnv.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/it/ITReadOnlySpannerTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/it/ITReadWriteAutocommitSpannerTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/it/ITSqlMusicScriptTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/it/ITSqlScriptTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/it/ITTransactionRetryTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITAsyncAPITest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBackupTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITClosedSessionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITCommitTimestampTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseAdminTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITDatabaseTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITInstanceAdminTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITQueryOptionsTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITQueryTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITTransactionManagerAsyncTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITTransactionManagerTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITTransactionTest.java
Labels: cla: yes

#381 refactor: adds git pre-commit hook
  git-hooks/pre-commit
Labels: cla: yes

#384 chore: regenerate README
  README.md
  synth.metadata
Labels: cla: yes, context: none

#386 fix: sets the project for the integration tests
  CONTRIBUTING.md
  google-cloud-spanner/pom.xml
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/IntegrationTestEnv.java
Labels: cla: yes

#388 feat: adds clirr check on pre-commit hook
  git-hooks/pre-commit
Labels: cla: yes

#394 samples: add presubmit lint check
  .github/workflows/samples.yaml
  CONTRIBUTING.md
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: partial

#379 feat: support setting timeout per RPC
  google-cloud-spanner/pom.xml
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerOptionsTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
Labels: api: spanner, cla: yes

#397 build: temporarily disable reporting to unblock releases
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#398 fix: remove potential infinite loop in administrative requests
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
Labels: api: spanner, cla: yes
