Repository googleapis/java-spanner, pull requests merged in 2021-02, with the labels that each got.

#828 chore: updates flakybot to new name buildcop
  .kokoro/build.sh
  synth.metadata
Labels: api: spanner, cla: yes, context: none

#835 test: reduce wait time for BackendExhaustedTest
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerImpl.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/BackendExhaustedTest.java
Labels: api: spanner, automerge, cla: yes, type: cleanup

#839 build: migrate to flakybot
  .kokoro/build.sh
  synth.metadata
Labels: api: spanner, cla: yes, context: full

#841 test: suppress logging a known warning
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/SpannerPoolTest.java
Labels: api: spanner, cla: yes, type: cleanup

#843 chore: make compiled statements immutable
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ClientSideStatementExecutor.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ClientSideStatementImpl.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ClientSideStatementNoParamExecutor.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ClientSideStatementSetExecutor.java
Labels: api: spanner, cla: yes, type: cleanup

#844 cleanup: return instead of fallthrough + improve comment
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
Labels: api: spanner, cla: yes

#845 build(java): generate docfx yml on release
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#846 build(java): run linkage monitor as GitHub action
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#851 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/auto-release.yaml
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: automerge, cla: yes, context: full

#858 cleanup: remove unused transaction manager
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SingleUseTransaction.java
Labels: api: spanner, cla: yes

#840 test: force-close to speed up timeout tests
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionImpl.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SpannerPool.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/StatementExecutor.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/ForceCloseSpannerFunction.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/AbstractMockServerTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/SpannerPoolTest.java
Labels: api: spanner, cla: yes, type: cleanup

#859 docs: generate sample code in the Java microgenerator
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/DatabaseAdminClient.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/package-info.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/instance/v1/InstanceAdminClient.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/instance/v1/package-info.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/SpannerClient.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/package-info.java
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full, samples

#855 fix(3.1.x): blanks span for session keepAlive traces
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
Labels: api: spanner, cla: yes

#856 fix(3.1.x): UNAVAILABLE error on first query could cause transaction to get stuck
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractReadContext.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/AbstractReadContextTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginTransactionTest.java
Labels: api: spanner, cla: yes

#863 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#864 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#866 chore(3.1.x): release 3.1.5-SNAPSHOT
  google-cloud-spanner-bom/pom.xml
  google-cloud-spanner/pom.xml
  grpc-google-cloud-spanner-admin-database-v1/pom.xml
  grpc-google-cloud-spanner-admin-instance-v1/pom.xml
  grpc-google-cloud-spanner-v1/pom.xml
  pom.xml
  proto-google-cloud-spanner-admin-database-v1/pom.xml
  proto-google-cloud-spanner-admin-instance-v1/pom.xml
  proto-google-cloud-spanner-v1/pom.xml
  samples/snapshot/pom.xml
  versions.txt
Labels: api: spanner, cla: yes, type: process

#867 docs: libraries-bom 16.4.0
  README.md
Labels: api: spanner, cla: yes

#873 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#876 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#878 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#544 feat!: add support for CommitStats
  google-cloud-spanner/clirr-ignored-differences.xml
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncRunner.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncRunnerImpl.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncTransactionManager.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AsyncTransactionManagerImpl.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/CommitResponse.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/CommitStats.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/Options.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionImpl.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPoolAsyncTransactionManager.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionManager.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionManagerImpl.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunner.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncRunnerImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncRunnerTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncTransactionManagerImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncTransactionManagerTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/BaseSessionPoolTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/CommitResponseTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginTransactionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/OptionsTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/RetryOnInvalidatedSessionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SessionPoolTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionContextImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionManagerImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionRunnerImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ReadWriteTransactionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/SingleUseTransactionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITAsyncAPITest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITTransactionManagerTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITTransactionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITWriteTest.java
Labels: api: spanner, cla: yes

#452 feat!: Point In Time Recovery (PITR)
  google-cloud-spanner/clirr-ignored-differences.xml
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/Backup.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/BackupInfo.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/Database.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseAdminClient.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseAdminClientImpl.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseInfo.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/testing/RemoteSpannerHelper.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/testing/TimestampHelper.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/BackupTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseAdminClientImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseAdminClientTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITBackupTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITPitrBackupAndRestore.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITPitrCreateDatabaseTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITPitrUpdateDatabaseTest.java
Labels: api: spanner, cla: yes

#871 fix: allows user-agent header with header provider
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
Labels: api: spanner, cla: yes

#879 docs: Add OpenCensus to OpenTelemetry shim to README
  README.md
Labels: api: spanner, cla: yes

#882 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#886 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#887 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#890 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#888 test: removes flaky close result set test
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/InlineBeginTransactionTest.java
Labels: api: spanner, cla: yes

#885 fix: wrong use of getRetryDelayInMillis() / 1000 in documentation and retry loops
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/DatabaseClient.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerExceptionFactory.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionRunnerImpl.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ReadWriteTransaction.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/AsyncTransactionManagerTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/DatabaseClientImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/RetryOnInvalidatedSessionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/TransactionManagerAbortedTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionAsyncApiAbortedTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ITAbstractSpannerTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ReadWriteTransactionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITClosedSessionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITTransactionManagerAsyncTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITTransactionManagerTest.java
Labels: api: spanner, automerge, cla: yes

#891 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: api: spanner, cla: yes, context: full

#894 test: close Spanner instance after test
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
Labels: api: spanner, cla: yes

#898 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: spanner, cla: yes, context: full

#904 test: fixes gapic spanner test
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
Labels: api: spanner, cla: yes

#905 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#907 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#908 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#910 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#912 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#608 feat!: add CommitStats to Connection API
  google-cloud-spanner/clirr-ignored-differences.xml
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/CommitResponse.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/Connection.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionImpl.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionOptions.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionStatementExecutor.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ConnectionStatementExecutorImpl.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/DdlBatch.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/DmlBatch.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ReadOnlyTransaction.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ReadWriteTransaction.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/SingleUseTransaction.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/StatementResult.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/UnitOfWork.java
  google-cloud-spanner/src/main/resources/com/google/cloud/spanner/connection/ClientSideStatements.json
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/CommitResponseTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/AbstractConnectionImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ClientSideStatementsTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ConnectionImplTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/DdlBatchTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/DmlBatchTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ReadOnlyTransactionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ReadWriteTransactionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/SingleUseTransactionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/it/ITCommitResponseTest.java
  google-cloud-spanner/src/test/resources/com/google/cloud/spanner/connection/ClientSideStatementsTest.sql
  google-cloud-spanner/src/test/resources/com/google/cloud/spanner/connection/ConnectionImplGeneratedSqlScriptTest.sql
Labels: api: spanner, cla: yes

#915 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes
