Repository googleapis/java-spanner, pull requests merged in 2021-08, with the labels that each got.

#1329 chore: fix checker-qual dependency issue
  pom.xml
Labels: api: spanner, cla: yes

#1321 chore: autosynth
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/DatabaseAdminClient.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/admin/database/v1/DatabaseAdminClientTest.java
  synth.metadata
Labels: api: spanner, cla: yes, context: none

#1303 samples: add default leader options samples
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/com/example/spanner/CreateDatabaseWithDefaultLeaderSample.java
  samples/snippets/src/main/java/com/example/spanner/GetDatabaseDdlSample.java
  samples/snippets/src/main/java/com/example/spanner/GetInstanceConfigSample.java
  samples/snippets/src/main/java/com/example/spanner/ListDatabasesSample.java
  samples/snippets/src/main/java/com/example/spanner/ListInstanceConfigsSample.java
  samples/snippets/src/main/java/com/example/spanner/QueryInformationSchemaDatabaseOptionsSample.java
  samples/snippets/src/main/java/com/example/spanner/UpdateDatabaseWithDefaultLeaderSample.java
  samples/snippets/src/test/java/com/example/spanner/CreateDatabaseWithDefaultLeaderSampleIT.java
  samples/snippets/src/test/java/com/example/spanner/GetDatabaseDdlSampleIT.java
  samples/snippets/src/test/java/com/example/spanner/GetInstanceConfigSampleIT.java
  samples/snippets/src/test/java/com/example/spanner/ListInstanceConfigsSampleIT.java
  samples/snippets/src/test/java/com/example/spanner/QueryInformationSchemaDatabaseOptionsSampleIT.java
  samples/snippets/src/test/java/com/example/spanner/SampleTestBase.java
  samples/snippets/src/test/java/com/example/spanner/UpdateDatabaseWithDefaultLeaderSampleIT.java
Labels: cla: yes, api: spanner, samples

#1335 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: spanner, automerge

#1343 test: use unique name for threads in test
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpc.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SpannerThreadsTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/spi/v1/GapicSpannerRpcTest.java
Labels: cla: yes, api: spanner

#1334 feat: release gapic-generator-java v2.0.0
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/DatabaseAdminClient.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/DatabaseAdminSettings.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/stub/DatabaseAdminStubSettings.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/database/v1/stub/GrpcDatabaseAdminStub.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/instance/v1/InstanceAdminClient.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/instance/v1/InstanceAdminSettings.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/instance/v1/stub/GrpcInstanceAdminStub.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/admin/instance/v1/stub/InstanceAdminStubSettings.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/SpannerClient.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/SpannerSettings.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/GrpcSpannerStub.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/v1/stub/SpannerStubSettings.java
  renovate.json
  synth.metadata
Labels: cla: yes, api: spanner, context: partial

#1348 chore: release gapic-generator-java v2.0.1
  renovate.json
  synth.metadata
Labels: cla: yes, api: spanner, context: partial

#1350 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: spanner, automerge

#1352 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: spanner

#1359 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: spanner, automerge

#1358 test: unskip cmmr tests
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/test/java/com/example/spanner/CreateDatabaseWithDefaultLeaderSampleIT.java
  samples/snippets/src/test/java/com/example/spanner/GetDatabaseDdlSampleIT.java
  samples/snippets/src/test/java/com/example/spanner/QueryInformationSchemaDatabaseOptionsSampleIT.java
  samples/snippets/src/test/java/com/example/spanner/SampleTestBase.java
  samples/snippets/src/test/java/com/example/spanner/UpdateDatabaseWithDefaultLeaderSampleIT.java
Labels: cla: yes, api: spanner

#1355 chore: remove grpc-gcp version from pom.xml
  google-cloud-spanner/pom.xml
Labels: cla: yes, api: spanner

#1362 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: spanner, automerge

#1363 feat: use dummy emulator-project when no project is set
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java
Labels: cla: yes, api: spanner

#1366 feat: configure initial sp version
  .github/workflows/ci.yaml
  .github/workflows/integration-tests-against-emulator.yaml
Labels: cla: yes, api: spanner

#1365 build: configure branch 6.4.4-sp as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: spanner

#1368 chore: remove linkage monitor ci step
  .github/workflows/ci.yaml
Labels: cla: yes, api: spanner

#1300 chore: add dependencyDashboardLabels to renovate.json
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  renovate.json
  synth.metadata
Labels: cla: yes, api: spanner, context: full

#872 feat: add support for JSON data type
  google-cloud-spanner/clirr-ignored-differences.xml
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractStructReader.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/ForwardingStructReader.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/Key.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/ResultSets.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/Struct.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/StructReader.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/Type.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/Value.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/ValueBinder.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ChecksumResultSet.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/DirectExecuteResultSet.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ReplaceableForwardingResultSet.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/AbstractStructReaderTypesTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/GrpcResultSetTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/KeyTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/MockSpannerServiceImpl.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/ReadFormatTestRunner.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/ResultSetsTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/TypeTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/ValueBinderTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/ValueTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/DirectExecuteResultSetTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/RandomResultSetGenerator.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ReadWriteTransactionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ReplaceableForwardingResultSetTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITQueryTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITWriteTest.java
  google-cloud-spanner/src/test/resources/com/google/cloud/spanner/read_tests.json
Labels: cla: yes, api: spanner, automerge

#1380 ci: removing linkage-monitor from the required checks
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: spanner, automerge

#1382 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: spanner, automerge

#1371 chore: remove unused steps from sync repo settings
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: spanner

#1383 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: spanner, automerge

#1375 chore: add samples for JSON
  samples/snippets/src/main/java/com/example/spanner/AddJsonColumnSample.java
  samples/snippets/src/main/java/com/example/spanner/QueryWithJsonParameterSample.java
  samples/snippets/src/main/java/com/example/spanner/SpannerSample.java
  samples/snippets/src/main/java/com/example/spanner/UpdateJsonDataSample.java
  samples/snippets/src/test/java/com/example/spanner/SpannerStandaloneExamplesIT.java
Labels: cla: yes, api: spanner, automerge, samples

#1395 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: spanner, automerge

#1398 build(java): update renovate config to mark conformance tests as a test commit type
  renovate.json
  synth.metadata
Labels: cla: yes, api: spanner, automerge, context: full
