Repository googleapis/java-spanner, pull requests merged in 2022-12, with the labels that each got.

#2185 ci: configure the protected branch
  .github/workflows/ci.yaml
  .github/workflows/integration-tests-against-emulator.yaml
Labels: api: spanner, size: l

#2184 feat: setting up 6.33.x branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: spanner, automerge, size: s

#2143 refactor: Removing duplicated code to handle array values
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/StructReader.java
Labels: api: spanner, size: m

#2195 chore: make Partition class getters public
  README.md
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/Partition.java
Labels: api: spanner, automerge, size: xs

#1930 chore: mark native image checks as required
  .github/sync-repo-settings.yaml
Labels: api: spanner, size: xs

#2198 chore: Adding missing slash
  .kokoro/build.sh
  README.md
Labels: api: spanner, size: xs

#2172 feat(spanner): add samples for fine grained access control
  README.md
  samples/snippets/src/main/java/com/example/spanner/AddAndDropDatabaseRole.java
  samples/snippets/src/main/java/com/example/spanner/EnableFineGrainedAccess.java
  samples/snippets/src/main/java/com/example/spanner/ListDatabaseRoles.java
  samples/snippets/src/main/java/com/example/spanner/ReadDataWithDatabaseRole.java
  samples/snippets/src/test/java/com/example/spanner/DatabaseRolesIT.java
Labels: api: spanner, samples, size: l

#2207 chore: fix kokoro windows java 8 ci by setting JAVA11_HOME env variable
  .kokoro/build.bat
  owlbot.py
Labels: api: spanner, size: xs

#2210 chore: ensure that java8 is used to run tests in kokoro windows job
  .kokoro/build.bat
Labels: api: spanner, automerge, size: xs

#2209 test: add tests for JSONB array support
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITPgJsonbTest.java
Labels: api: spanner, size: m

#2155 feat: Support for Proto Messages & Enums
  google-cloud-spanner/clirr-ignored-differences.xml
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractResultSet.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/AbstractStructReader.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/ForwardingStructReader.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/Key.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/ResultSets.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/Struct.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/StructReader.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/Type.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/Value.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/ValueBinder.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ChecksumResultSet.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/DirectExecuteResultSet.java
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/connection/ReplaceableForwardingResultSet.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/AbstractStructReaderTypesTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/GrpcResultSetTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/MutationTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/ResultSetsTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/SingerProto.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/TypeTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/ValueBinderTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/ValueTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ChecksumResultSetTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/DirectExecuteResultSetTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/RandomResultSetGenerator.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ReadWriteTransactionTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/connection/ReplaceableForwardingResultSetTest.java
  google-cloud-spanner/src/test/resources/com/google/cloud/spanner/singer.proto
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/Type.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/TypeCode.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/TypeOrBuilder.java
  proto-google-cloud-spanner-v1/src/main/java/com/google/spanner/v1/TypeProto.java
  proto-google-cloud-spanner-v1/src/main/proto/google/spanner/v1/type.proto
Labels: kokoro:force-run, do not merge, kokoro:run, api: spanner, size: xl
