Repository googleapis/java-spanner, pull requests merged in 2022-01, with the labels that each got.

#1559 samples: add GFELatency metrics to TracingSample
  samples/snippets/src/main/java/com/example/spanner/TracingSample.java
Labels: cla: yes, api: spanner, samples

#1581 test: only use one backup for integration test
  README.md
  google-cloud-spanner/pom.xml
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/slow/ITBackupTest.java
Labels: api: spanner, automerge

#1639 chore: change name to api_shortname in .repo-metadata.json
  .repo-metadata.json
Labels: api: spanner, automerge, owlbot:ignore

#1630 feat: Updating readme with new gfe latency metrics
  .readme-partials.yaml
Labels: api: spanner

#1649 chore: update release-level in .repo-metadata.json
  .repo-metadata.json
Labels: api: spanner, automerge, owlbot:ignore
