Repository googleapis/java-spanner, pull requests merged in 2023-01, with the labels that each got.

#2211 samples: Adding samples for updating & querying Proto messages & enums
  samples/snippets/src/main/java/com/example/spanner/QueryProtoColumnSample.java
  samples/snippets/src/main/java/com/example/spanner/SingerProto.java
  samples/snippets/src/main/java/com/example/spanner/UpdateProtoColumnSample.java
Labels: api: spanner, samples, size: xl

#2212 test: Proto Column Integration tests
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/it/ITProtoColumnTest.java
Labels: api: spanner, size: l

#2218 Configured jitpack.yml to use OpenJDK 11
  jitpack.yml
Labels: api: spanner, size: xs

#2111 fix: retry on RST_STREAM internal error
  README.md
  google-cloud-spanner/src/main/java/com/google/cloud/spanner/IsRetryableInternalError.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/IsRetryableInternalErrorTest.java
  google-cloud-spanner/src/test/java/com/google/cloud/spanner/PartitionedDmlTransactionTest.java
Labels: api: spanner, size: m

#2224 chore: Updating Integration tests service account
  .kokoro/nightly/integration-staging.cfg
Labels: api: spanner, size: xs

#2229 chore: Updating instance name
  .kokoro/build.sh
Labels: api: spanner, automerge, size: xs

#2236 chore: Adding Kokoro Configurations to run integration tests against staging and devel environment.
  .kokoro/build.sh
  .kokoro/continuous/integration-cloud-devel.cfg
  .kokoro/continuous/integration-cloud-staging.cfg
  .kokoro/nightly/integration-cloud-devel.cfg
  .kokoro/nightly/integration-cloud-staging.cfg
Labels: api: spanner, size: m
